export const SERVER_CREATE_GAME = 'server/create_game'
export const SERVER_GET_FIGURE = 'server/get_figure'
export const SERVER_SET_FIGURE = 'server/set_figure'
export const SERVER_GET_GAME_LIST = 'server/get_game_list'
export const SERVER_UNSUBSCRIBE_GAME_LIST = 'server/unsubscribe_game_list'

export const CLIENT_CREATE_GAME = 'client/create_game'
export const CLIENT_ERROR = 'client/error'
export const CLIENT_NEW_PLAYER = 'client/new_player'
export const CLIENT_GET_FIGURE = 'client/get_figure'
export const CLIENT_SET_FIGURE = 'client/set_figure'
export const CLIENT_UPDATE_COMPETITOR_SPECTRE = 'client/update_competitor_spectre'
export const CLIENT_COMPETITOR_DISCONNECTED = 'client/competitor_disconnected'
export const CLIENT_UPDATE_GAME_LIST = 'client/update_game_list'
